#!/usr/bin/env bash
set -euo pipefail
PAT="As an AI|Certainly!|This function.*generated by AI|TODO: AI|—"
if grep -R -E -n -- "$PAT" --include="*.ts" --include="*.tsx" --include="*.md" app lib components docs 2>/dev/null | grep -v "check-ai-pattern" | grep -q .; then
  grep -R -E -n -- "$PAT" --include="*.ts" --include="*.tsx" --include="*.md" app lib components docs 2>/dev/null | grep -v "check-ai-pattern"
  echo "FAIL AI pattern detected"; exit 1
fi
echo "ai-pattern check pass"
