#!/usr/bin/env bash
set -e
PAT="As an AI|Certainly!|In conclusion|This function.*generated by AI|TODO: AI|—"
if grep -R -E -n "$PAT" --include="*.ts" --include="*.tsx" --include="*.md" app lib components docs 2>/dev/null | grep -v "check-ai-pattern"; then
  echo "FAIL AI pattern detected"; exit 1
fi
echo "ai-pattern check pass"
